
<select id="<?= $this->getId();?>" name="<?= $this->getName(); ?>" <?= (!$this->getMultiple()) ?: 'multiple="multiple"'; ?>class="<?= $this->getClass();?>"<?=(!$this->getRequired()) ?: ' required' ?><?= (!$this->getDisabled()) ?: ' disabled';?>>
<?php foreach ($this->getOptions() as $value => $label): ?>
    <option value="<?= $value ?>"<?= ($value != $this->getValue()) ?: ' selected'?>><?= $label ?></option>
<?php endforeach; ?>
</select>